apiVersion: v1
kind: Secret
metadata:
    name: image-audit
    namespace: image-audit
stringData:
    #ENC[AES256_GCM,data:XkyuOxLEXdWEPoY93rq2z8RMvjkUeiDQgXTeAEVjjG6q4fE8Ua5HptlMYDZnDJ1XKDQZcW8qxyQSCV4WEL4Oqdl/Mjt4PmyiKV/v5wQl5zmTjLmxBin5,iv:8Lfgg7udQ3Qcu0jTRIkgle5Vo/fW73YSgz8OhP+zXzA=,tag:HTNsTKY+vN/5T+TbCoRI/g==,type:comment]
    VIKUNJA_TOKEN: ENC[AES256_GCM,data:MIVJoc1t2x5G/9VYD4nShC9MFVvVSLdZJDJTcI9QIdL7EQPtQxB6eusMLA==,iv:qIrlQ/Fi27oDFyu2di1rQMG5uo+ZMsi0c59+QF1gyWI=,tag:PLbSItxMgM5Km1U1Pf+MYg==,type:str]
    #ENC[AES256_GCM,data:eH/AKHnE9ke3zq49tKxqzdGD8rv6anE+5TP9Kxjr+6oP1j1KgWW4USBYgcwAwLt9rV30Od/q7sPewIjXhMzzpTz/7WC8iFJ8sTTWG7OarNrkszpXJNo=,iv:W2AXiHgC6AyeZGER9qBPxwsEHo00gMGqKpSPx/dAsNU=,tag:qsBoxGN5k5HoMAR23xOqCw==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:qRuC75Q4qaa+HhBWtPMYeSiWCIdTVDP+sbL9m56cmf9jW1RacBMw6dhNfuQsG1FRFcvGtzKDq31/+kIUktsvMx2QmL407TuVAXTockTE2r2zrsQPUjKcR9KUOSe6,iv:K6M26ZP6chO+lmevfg7kyUqh3W8lR2YYFltU+ntgZ3s=,tag:DJPU/gPX/sUjaouWb8lP1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZR1RTOHJIOTU1a29RMzdJ
            RysvVXNQdHl0NnVtU2xsVkFFNXFHOXoraWpjCklRenF1SWdzTFRzRktYMHFHY3RZ
            ekZjd205YWtJR2VaTHRRbEp1b2d5YzgKLS0tIFZnMzhOWlZSdXBHdVhCeU9oT3d1
            Rm5OV1psS25QeG4vSWRyd3R6bE1Qa3MKP4S2VWgS8m4S198aB6baQ++yVL0T78RO
            w2wwtOMJO/eTj2R0Ll7+2nq9XewOat7p0a4CCz/Wu2cmCu5tD6Kl8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T12:18:38Z"
    mac: ENC[AES256_GCM,data:YDAheaAJrxvxzfhaFWsC4wPVc6JsummvAC8VEsGdNoVIFY0upwdKyVlsqo/JBzvp5IJWVU4Au5kyEN7iEkXI3zMF/l0Frh7OxWa9JyDfQ76nOom1Xqc+DcFWp21xzO1gwgQWYwpU6nxgHrVG+SZlsP+eFmv3GDgbMmEtAbtoDCw=,iv:Fcg8hEaww2IJk5Pdgp8aRGpvTnPSFKTGfd4sgEWzV9U=,tag:tXzKetsn2uIa/eftSErn5Q==,type:str]
    version: 3.13.3
