apiVersion: v1
kind: Secret
metadata:
    name: image-audit
    namespace: image-audit
stringData:
    #ENC[AES256_GCM,data:06kVUmG86wowJiYAsDiWype8cmNTS5KJpAGLuPNGilItevOPK3ZP948KoKLWctYawoiYKwKzH3VYjEXTt2T2g2MVOFAx+CuD+f2w8ixPf+Jveg==,iv:BB+EMU58kbD9vUtm2xbgw01WBKXZOWHHVkAWOLZqxFM=,tag:YWh8OcIIAvdyBURLuyo1Xw==,type:comment]
    VIKUNJA_TOKEN: ENC[AES256_GCM,data:wetuLOZ1JbAZ2coWglj6YbKs9Z9XVa3+LcWigwZh63aVmoi1TeJbuSXy1A==,iv:pEZIW1vjw1MOJxsuqJ6FvnSoYwm0L25MDr9s7cVWkfI=,tag:eGdtg0hPz+Ji6DxbfpNqbw==,type:str]
    #ENC[AES256_GCM,data:KrixV+uAffvXguv8H3c6APcouYjimZ5h8UoVPom1+DiRWRzWglOqFESqDUBMTUFLAQCm+E5HVhIgojWUqTkseTheWEtIacFFjau6sc10/kaIzd3dLQc=,iv:hMJbuHN/LxfTFlT1HW8QYmod5yM20Fxa7UHwaDnYgk4=,tag:YT14eTblLsL9kHifT7JDgA==,type:comment]
    GITHUB_TOKEN: ENC[AES256_GCM,data:tv0gwQB7I4oRxK2TghprnNTlzzA/kSwCy4hr0uRH+w0MSOpazRq1Vfn7vuACDk9naVeeP9g+mV7yRuTMM21ZPcEzvuFbJSu8jhU2rvRAwP0whVbQTx4GYKBxJc4b,iv:z34YjqNWxuyQ/oWSIk1Q/kfIiV1b5NM3MTaARhcNfJc=,tag:pv0AktK99tx8jpBGrCNJlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OWRJY1pZNjIrZlA4dlEx
            ZFdUS0VwdlIrcCt2TDd3MWE3a01LVElic1NjCnArR3FLNHNhUWFEN0EwM3JCbmQ2
            ZU9DQUxNU2tJdzBQbW10UTRMKzNlV0EKLS0tIFZnVmNsUTNaUktmWlg2cG5pZkFM
            bDYyd2lOSEhiWFFnWC9GWkp0MzVubTQKkaIr56dUjHZ8aE9M5R8ZrJ5OPK5VDv5D
            owE1rucLBt3+LUSWaIIjpTM5ysxP1jDvbjQJa38QIqNfkalNGjwxsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T12:12:04Z"
    mac: ENC[AES256_GCM,data:WmuvghqLBv6DnVhd3mx2thvGQyPXR4SrdaTjB/mHjLsdSiU5XRWTf5WPW49W9YdWyQTOfiZ90WE3k9xCimg4o/NbJkSx7RSsHyxB8gs14IZk6/G3PMdHm+OzbP2EO0W6FOxi94lBp75wZpJEJEck20OcLWQ1Vt4jEiAZUwesNG8=,iv:MM0TSIEmNhII0iLa0zbKjZHGX2jSXstBZErZA9pDer0=,tag://NDsQWAxhCoj/DNhPTNPg==,type:str]
    version: 3.13.3
