apiVersion: v1
kind: Secret
metadata:
    name: image-audit
    namespace: image-audit
stringData:
    #ENC[AES256_GCM,data:aPfGPTM58IW3NSUAC4NpZ4iB/E9Fisrbx470fClVvNmkpbGDjl7RpAjEc1uMcA2FirXVWWOha4irKjIlQ7ABmJueXjeeGTdv3cFokNNZUKluBJUNO6+vrtQPWvFJUdwEGoM2YdBPO61QVO8OmGuobw==,iv:Q6oHZ33cznWOG0U5AmPtR5HaJi9WHDaVsqxEadoZRgs=,tag:C0MtSNNolwwcAGs+PtkuOw==,type:comment]
    VIKUNJA_TOKEN: ENC[AES256_GCM,data:J72UK9fgH+UPfQ==,iv:MNldKCoBwBKhttHBZJNAX5YXjl/W6/F/IF+68N5kErU=,tag:9ZQLQgpPqMLtxMVkbFOG9Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSjlRNkN0M2NNQkREcTJ3
            K2VsMEFXVGJmMFNMWUFrV1pJcm9OdWFRUlhjCnBSQy9kYllpT040aVRmdmNFNCtt
            cWdHdTZuOUJSOFBrMm5IdlVkOXV6TUkKLS0tIFU5a01XcGIwMS9lVCszSVM5WjR5
            U203Ly90VlZJT3ZMUEpsQTNYRUFPV1EKC3tCdqjgdRAk3hIBlEDGSRKUkebCih07
            EqsS0zXFCgyznmegcCKGNRpmsck+B4mb+wLznpGK74EDpKxL0JtOvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T12:03:48Z"
    mac: ENC[AES256_GCM,data:bTLYATIz/Y1Don+iMiR3tpf70wRYfi5KGlJIT+1huC+BpjTyJ8cCuonLxZ7zC3rCnSYVQBSPsL2Wd7YgVWjZ/P4/vtTVKD81W5Muc1c5PPS3pxyVroDuIKt1izzu2FiTs/NwuM415RLcWO4RuAhW1/chl8BSSk1SX5BFCpcjyGA=,iv:Zoqh6y3GEBH3joMBVFwD1n/q7v2zXBtPGTgukG8JtgE=,tag:fXUtr0IXwalNena8Nsd2Nw==,type:str]
    version: 3.13.3
