machine:
  network:
    nameservers:
      - 192.168.1.1
      - 1.1.1.1
      - 8.8.8.8
  time:
    servers:
      - time.cloudflare.com
  features:
    hostDNS:
      enabled: true
  sysctls:
    net.ipv4.conf.all.send_redirects: "0"
    net.ipv4.conf.default.send_redirects: "0"
    net.ipv4.conf.ens18.send_redirects: "0"

cluster:
  allowSchedulingOnControlPlanes: true
  proxy:
    disabled: true
  network:
    cni:
      name: none

