apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
stringData:
    #ENC[AES256_GCM,data:9uHZPZMTy1ii0uab6W0qmHQoJYC+legsgALqsqdRHweW+1ekEjn6uLF6ojkFFc4UqFnQNn0nZLl4N1sRs15d/J17MFQ=,iv:yWbizO0RiSDt11YpFdyy7BqKOVJvXkyf/2/DYv9HkjQ=,tag:pr5hLs1XAdrSa0FmJHNVhQ==,type:comment]
    api-token: ENC[AES256_GCM,data:rKdjlDteYOJRsGV9S4FDH7/yf9ZMdiRmaNwJz4yH+UTnn2iy3+AlVZKt3hJJtbbyz79LO1A=,iv:Amcdt19Egal849Vpqmz86ja96fdkc0xux2z1SYt+HZE=,tag:mMSExv+dEqJz5X1M3fitIw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYVpML2U1U2hqZ3JwSUtY
            aXMra2Q0ZkRrZHN0T09MV1JzQTl1SVcwYkRJCi9OQllKRDcwNWsvaDVUa0NzcUZn
            dTlUS3luUU5paDNrR0JWdXNXWGVSQlkKLS0tIFZpeGRCQXk0dGFkdDhGcnZGSjJW
            emF0T1BGU2JuOFlkL1VQcTlvT2UyUDQKkQoNr24PlR9oTEOkQBo3XMF0bnX1CBRU
            q1oACBbf3ONDRpEXryHucYwYmLyIR0ar83mjiB/85INok/7qnw9EXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T10:12:46Z"
    mac: ENC[AES256_GCM,data:tuvEakxeKjgHmKThE2OZuFOXGFaeag9qJBsRDQqXQgtMn3IAxMEJ4GzViHj/9GepKcpgt42TVfMeS8mTkGxfO65/prUSLgt4k3rVSUiGrJeXj6cxwV4+J8wvgmwl9MC/m+n5p1w0+X4/YJyajuLh+DdvDO+kBRJiov9ZzSopFPQ=,iv:gEByXj90kWZjI/xB0b0GbQs2ojLMgNNhcAds5euS+FE=,tag:kvvO8TchutwJo29nKPkrdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
