apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:S89C0j4WOoKxFEJi0XvT6A==,iv:V8t5+Y45PjS/C9EHQWIijZCcRbHXlzBk9jwed2vy18s=,tag:J5AqnL5I7bRGr49C2ZXdCA==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:6MwlKh/BLtFZqXplFtub3IcAlg6TUSji3vkWbt4QbBd7o6BM,iv:t0Jvr8fKU0BVy07/c8S6fopyiywHa63A9xPPm1Y1VIo=,tag:INv270JRSbnFYFKgEVWBqA==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:9hKuJOaGQ3i7wnvFar3fA1ECnjDQZT4Uw3TvmlUi6i6w6/ZueO/5tPjAXnUV5O158vhjhaiQ8TRq11eY,iv:FkF9bSKYEBcSfAqdK8oZNP/jTIJo7TrqNSouqTqQg10=,tag:mIhxyFh2JACavf0gmOZaIw==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:EDU7N0YjrU9iUp+3j1NpnTjieJ/lX2VodcwylOiJr32oKs7/rvh4/0iDVUtrJxkvnpSpdvcB9C8tWxSziSlqZZJI,iv:ArKbY7QKp91ixv0b2Ndjh92o8AOidv/XMUv/kfcW+YM=,tag:eLnbChoOFQBPcH2uUAcozg==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:s/tu4U8E2XR4L1RHOtzxJ4SLYPzKAL8JshQWH5If/UM=,iv:qkFhtBw1mWafjRySgdhn0fobTQag+HelJWg9y79CWkg=,tag:PilQZbtOI5YzoNrEcIxIVA==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:MPZ5Cbzk+mTSDzC36bqVKgZVW0/ddjFrxsgn2OCone4=,iv:W9W26fPnt0iaavtVy2fB48E5AWHf6O0Q9C6AGyuNWYc=,tag:ezKHDAEsaiOjTDCy7kkokg==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:ENPO8+BPmvH0J9gOu7TXabUDjQ0hoEkw6u590uDenj4=,iv:ZRy1ZWN5BX2AhdD8kf7UIPw+phOOvdsjZOp9g5TxjKE=,tag:L9GGZmM9BYvnhr02mHnDXg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:svE9RcE=,iv:CjE+gNM7E2JDAWk18+pyiB6N1pOuysFs8o1cpL6iZyo=,tag:AN4l6GiF3vbTB9hSDhf3/A==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:ETISWG1s3UBv/w==,iv:yfvfUFL8rFqCeyIkH3LtQ+WCp3GwjTBHzIMITPOI6Kw=,tag:B/iGOOgsRQnANnAmQx0ylw==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:GfPEgJjUulBG6CHeX8QMgbyaoXGAYYU3yAE/nOADNXE=,iv:hDXHPLRbCbANUmzxv2OmMLtiv/vacXhimFU/DcicW/8=,tag:2AVxtirvHaxWGYrwu8VzuQ==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:IRuemSKTlzQk3jkX1akNgd2dajrUVMk7J83yg3hX+sIL7fokjSdCgdi5Qymwx7wzzOkZ+rcUsvAlIaYZer7rFvmjWm0=,iv:7779jbBPrDZ4BJT1WG3MjEwFYaUxJULkQFx6mcrhLhQ=,tag:m8BJxoQXu/7Y9IOBcrMxKw==,type:str]
    HOMEPAGE_VAR_TAUTULLI_KEY: ENC[AES256_GCM,data:ZFQKO4205lHVa1vONYeJFpK6M7mEPRdO1E8nn7z5Vb0=,iv:+V7gcVXulCbwk/f+U38hjEnRL6j11nfNawFwaaRNTv0=,tag:kgYdZnr5Ei5HKNRaKmxepA==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:d5oK7RR4glC9wKDBdham/ksvzeE=,iv:1NBzUjmJ4ow4kPTia2RjjhxcgEVVmmYVcEWjjXGW31o=,tag:SUidijXpjaOPFhKL8sYHQQ==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:vcQSRPpib5CdPlMSpU8NMn1MWlQ=,iv:kanI038rk3zj/mYBlho2w7hm4viAtQg6YVgrZUJIBIY=,tag:n0xo+JOxf9os0DScB9vrgw==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:3m0YmIwnLSdeFUQZbnTCHuvj/glbmqGNbxe9digKVGQsK4A6qH+l0EQ=,iv:Le09EGkrfQur31oxed5CupeiE8WQYUqztKITT7v75hw=,tag:7jqxIT7twm5WrsSTVcVguA==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1THdjM3pTdWxqcnE3OGtL
            QnpueGRCVG5aMnFxa2NYVExwV3lMdzF3aUFFCms5K1EzbitHZ2VNQUFtb2dMZkFj
            VEVMNGpzb2dZM2QzMzJ1NWdzNjc4bEkKLS0tIGpqdE5Lbm45WU1EZm8rN1djMVE0
            OXNRdmlwMWJjVHVRWnRESnc4SGJ4MXcKrY1CScxROOpjEdaHZvlz4aM68TDVS6cH
            E1p+UjQR9ypcFvBoy7CRitJ9U6tZKo8smHbylIdofApZc4ekuSbV1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T13:14:33Z"
    mac: ENC[AES256_GCM,data:MFkfPyjizH5HTD+UnXHlG0YUB9em/MtVecLTWkOw8cWJyml10fbr50pci4jpbGejcCGqAnweFN70W0U3MRH3j44SAkOZHE1vydWX7ep2wZH29XcpCNYniuuYGs9Ep88qj6fBbDiClzdJCQmTeTcW5dxPyAhNTRDFGveOD0LD3jU=,iv:nM8f9TooiFlfK9Rpvq76469ivO/Z1UJMOLvk7L0zj84=,tag:Sctxldr3/cMJDLiliZ8qIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
