apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:A3fxmD1pJgodGah2JGelKQ==,iv:7jTuE/EZIxQx3AI/WKdSZTPA6z+MfQ+//PibpkrG868=,tag:uxAH6p8L0Q4J49NuZzI6/A==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:9+KQdDImelAr4qtpMH7Nc5M9SCzchh+X4IF94V74D2imyXwx,iv:qQo0w0l2I1FefKcEmpr/Dad42GFAkXY/hmecjz4tnFE=,tag:SMWjzSGV8JjOp+x7wxmZ+g==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:tQHxZSEewWh2jxzewXAWtJnadeP28aL+GaydKFWFlmBgzBFmDy7P7FdPYxjQkHBSdc+T8yKQKqCPmnmL,iv:S2cCVx42jRcx8stiu2CJ0CD48BPmQRgF5iqI7XxWLiY=,tag:Rktdze7xLrRt9k8+QTs6sw==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:dSGMMkSH5JHfadk5wS0XC2WY8S4T98a+1iT423s0bunsfP6KHR3NJzU1EZP1+Zltp+uhxDzo7W7CtFMMNUN5Rhfx,iv:f8xhAU9Yr99g/oeMArZhay959dw3U9jiv61mUiO3w9Q=,tag:zahvCkRHQ3KvoPRtycjR8g==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:hsm2m/XmjJLeFHMqOvN0kCLKiccBspmEh04zOj9HaFU=,iv:dna/omsLh1CgWxJ685r/UB2cyglcd9Ap0K0BzuVuJf8=,tag:wQ+fvX14rQoQ+uW7jQgV3A==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:FoMa2c+kSDlO/Fu01f9chG+ai+HiT0hbJoea5uZuCkE=,iv:Jz14D/TmYNX7KnvKTMlF2pUpaDssBoTPSfS2wN20nho=,tag:pQ8qeEkcoz8KzuZ4UWoJDA==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:KZaMcPavUVhcjzzCgJwtHrYYDvPW7QzK1xe5lfPZzkU=,iv:35Y4xcvTW8BdKh7dgRiLMpywY1tWN9+9fhSYtbQUm4A=,tag:6NN2phWhqws3818qhPd9QQ==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:u1YuWcc=,iv:0jGF7amiWFzXuRB+Z6JAZ/JhWJeDDU0nG9XlGvz9EDo=,tag:2j9zT7SoAOg9L3bZONtSkQ==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:AqzQBL4o8WZfEA==,iv:1heUSZ4m2NcY0PGRM78VdEW+8NyN17u8+gt8JcTZ27Y=,tag:MeEqMKZVzP500O+fk1knag==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:MQ0/zda12tTylKKfy8PHoyhFiGUX3KbiRxluM0+O6Tw=,iv:cOohiXdqAjoBbPQIpEdelg+bNN4HfC/98lEe3JlBJ4k=,tag:0kM04uZwJep7NFx24hNwsA==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:igYP0+G2KXkDO5oY8JKSRDZzb9qJTfao6G1+cuvUKdbyFtL+xBYB9QDfOZhBD/QO3Izv6nqf4t8TkI4tve6L/vm6yqc=,iv:Goa4HytdAp1GTc1YxNMZd+73ISbtp4E/Tal4upH3BUk=,tag:A1MoOKB7BtZRO4aAppm44g==,type:str]
    HOMEPAGE_VAR_TAUTULLI_KEY: ENC[AES256_GCM,data:pSz40W2g/DQAk8FFqW71wWjXSRE4OW69uJG/BIIk43U=,iv:QL+JskcLJhnEjIOvcUwEx2Qa3G3e8I9ijVtMzzGPXh4=,tag:BFy6LZ/P/rliQLqO9pom2g==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:qK/3oQMXdvVOGvPFiV3AzghdHos=,iv:qVIv2JQeFIiXfzi/j42PrvNlakFZxULl9YlKdH+/bxA=,tag:Mq0R0q2N6DfUc5hXtACttw==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:gZwcCnhCLqki3a4UbPcZZGeLvqw=,iv:gaebXtXtpgbHx3FoEEOkyaz7riL7s89fMi3OvGr6Nho=,tag:vT9J8y1CPL+mTJxGG9u4KQ==,type:str]
    HOMEPAGE_VAR_IMMICH_KEY: ENC[AES256_GCM,data:hHx0/oSI+Rr6hBVbt4AZgGNPlO0empvYZ8a2rhTWGy6/BiiU5eSHGhg=,iv:KJmlbZ9NMCIj6qasZCFJ1GBtXYGrvPoFs6ak9T0rlwY=,tag:nPs65IBB7qgbfz4VhRtgfw==,type:str]
    HOMEPAGE_VAR_VIKUNJA_KEY: ENC[AES256_GCM,data:msyEGe05NM3MtfhqscLBwAU3OPULyp1aT/SoQ5gcFB4BTOSd+zX+eDNKbg==,iv:xMqjQjemSjStr15ZpT/tGzjGFBusaDdGMw6fwCjzKKc=,tag:N5qI6kLkca+SIjC5zVyzcA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Sm1tSHlGcXBFMm9sY3BN
            VmM3WFZSVnA1RnY4ak5NVmRBTWpkWmhTVUQwCjR4UTB6azJKbTBvQ3dRSFVLUjJZ
            ZVlFVHN6Qm1zQ1lJQkhFd2ZrQ2tyM3cKLS0tIHk0dWVTQzJDbzNjL2tSWHN0OWRM
            eXFKTDdXVkpzRjQzWkIwZ2xhMHphaHcKv4UR6IxGHeXduuM8bwIIDik/skpuqS8J
            0uOxOLBdN7qW5ckQdcrDK+PlRj8cYap1aY1kt8JsCG/7azu7/IDjpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:02:34Z"
    mac: ENC[AES256_GCM,data:HpWlOPD8bfkvlaFlGlStoXhmA2MB1q8wIPc3Z9BSJgZgKVqQbzmv6KaCQ/yrNlHfqkxzQZVW3L8z1VsKPw/bAhnh7KCLlPm+uWdTsKd/gk6J+Wg8Sq0U9NVY3CTgYZzlTsm4AoNPPPUdDvyr0NcAfja/kZbxib1kXGlr4T4uNOs=,iv:TTg6xVGw2h/aTU+SepoBCMDd8ZKQ+G0OzFPFIs6pipk=,tag:RNWa0JZvdKFeMYHbAiVVjQ==,type:str]
    version: 3.13.3
