apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
    namespace: homepage
stringData:
    HOMEPAGE_VAR_PROXMOX_USER: ENC[AES256_GCM,data:kBKE6/J5HvjQULXP10ZiwA==,iv:BRxpvoDyYDkzfQPR/InNYdfEPB88EJGanoCgfhhPVyU=,tag:CYq3b/TUeRb0P9PKXQLCJw==,type:str]
    HOMEPAGE_VAR_PROXMOX_KEY: ENC[AES256_GCM,data:/YeyPTSOjQtxkRRZJgxr6+jjj8fpChy3CqooprrpqN6SrpZ+,iv:aO6eMWqs0lDiK0U7Rueq/gT+EobKOGQHiaqyOiL5aT0=,tag:5QcTuwXfZZ465iHtUQZjzA==,type:str]
    HOMEPAGE_VAR_AUTHENTIK_KEY: ENC[AES256_GCM,data:whr/lziSeK3VLPosRuIe7Wt+5Skf1D2NHEuBxEJBE3FvGQb8oeg4LnwnFOm1cnteK3NgdTPKUuH7yRU0,iv:mgsEQvi4iHKVlXc39toalbHVi9PSlzT7CQCG+PTIdyo=,tag:iBwa8TBLwOcbwDWoyScm0g==,type:str]
    HOMEPAGE_VAR_TRUENAS_KEY: ENC[AES256_GCM,data:PHfvt28SbsSNyowNFEMpeXoLNn+QFJWxoA67Pmwhgmi5SE4m7ggOHhHvvesXd6Pd+YRqxyCgrya7J55Q0lYTMUWm,iv:bY6LjCEM3/mqf6ppY13M+FZOhC7lasTpzk1HB6Yt9NI=,tag:2RBuPWIV/EYAsGjOHFQmNw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:7lWhK/5Nhpb22jI+LcdNGNzggvbw09C9Px5ctw3rcdk=,iv:WpcStGUzfXWKorVsJlbt5MJm0n1gFhpsptRg0XcZMe0=,tag:EPhCq5pRBDpL5kW3Lf9BGQ==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:TbRWfty02FEoc1kqzVIpjT8vRJ7vvkrFzB5zUTlFTSg=,iv:NR2XsapBQ5QHfLsPAyW73/x0nfcPdzdgVHaoBsqatWM=,tag:PxbmbE/FykDCo/5HMXsvHg==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:y89K241afsZtGaAgNd9EAoUm1F27H4la6vbA40bvOe0=,iv:S7Y/y3lKdbJ5CaMBmlPu2EB1iAUI2BmhUdEOyCdSURM=,tag:qWUpngWWFx8aIhxT1ycdRw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:a8+q4uA=,iv:NwbO5iL3F5domrD8bjp5yama37PQ4wLPDXNPWiuWhyA=,tag:/YJPHSwTcDOfS/OiiN6YcA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:7EBGRMgHmyksoQ==,iv:ydRG9GJd8xBRxqbAju51QvZiYH/y4+4AIsr4/k5F7WA=,tag:NPwTuUsmlXA1SOADtH72CQ==,type:str]
    HOMEPAGE_VAR_BAZARR_KEY: ENC[AES256_GCM,data:Timre4LRobP9rAi0DS3CLMMHhX3OeG+Ezocivk2AdTY=,iv:DaOjXXPVc3U8snbwd7fPt0jIviV+HkxHPYhivzuV8sM=,tag:W2eVJrnOlFCQKcvHHeKsaA==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:bX/IWAZ2Mgk5Y3QdnOgYlgt1WxIFRMGrkDDDvnxwuw8eaFpcgBfhDw0KfVUvsVIjzu3VosqBuv/0tYYRQN3LQT6clP0=,iv:8QoQpxO7j+aszQgeZmWs1iVNSGRFLZNXhbKs1zLs+eM=,tag:zM+JH6+Agci79qm+7KW5Eg==,type:str]
    HOMEPAGE_VAR_TAUTULLI_KEY: ENC[AES256_GCM,data:6ZoBmTPRe5RZ6uqLemP5P7qUVCsBHK08K+1P6pzXQrc=,iv:0L+huqmmFs/P5yO4ueODLKpNsqwHJHmVyG2vl1eAi3g=,tag:gVZ2BY4jTwj2vwDinc5+nA==,type:str]
    HOMEPAGE_VAR_PLEX_TOKEN: ENC[AES256_GCM,data:k5ByQhoujY9yRU1ywmm0nOB5vKk=,iv:HRjHJ/e8SZVY/peQyomP1eyAO51hKGbYMyCovgULGck=,tag:qgc849D4ApygnEVOKiHtjg==,type:str]
    HOMEPAGE_VAR_ADGUARD_PASSWORD: ENC[AES256_GCM,data:pWSbN6N1M2Xb+oHJ8TNgegMlgHI=,iv:HAysfoSXdF8z0dnDtfGjQXD3RUCA9h6lNSHgE88FKak=,tag:Zx4f2GX8ljMGmVElM7xYAg==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSVZuekRpT1RrdzhaQjk4
            eFRBdGJCWkxXL2xWSm9xZFV2YlByOXpmVFE4CjBaZHpMS2Y3cURJMkw1MEZlRWlm
            UVcwOWsxMlF2dDE2UHd5MExCUDlNcjQKLS0tIGVrUEhUNXg1NEVwRWhZZHJFS1N0
            Q2JQbjJOa2lkTUxNMWd6TWpCMWdTL0kKjxQY9lrENQXes3jOCH5aCiFTtCtyqPoI
            RTY4VQKSpZCeP9xz5Juft4R0NNQTdvhuetxQqZ3VDO5xQSNKPdBlCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T13:11:28Z"
    mac: ENC[AES256_GCM,data:ef5CSbbJ7MxAdRO5UWXmyQHasS59eZ3sOJDfLYXGJnFW+S/nkAA4VYRB24Cq/PPFk8M2aKCz/hSpEz9WzWq6oVEzXr7ABYo+bMCrx/D6YP3Cwq0HYNg5NojIWu4C7y0G4Tw9vR59lfgdy7Q1yArd9xDUroSsLTg701HNDJRT99M=,iv:E+jSvd+EFlkk82P7q+RlmcLRReake/Uk/FKlj9L7jXY=,tag:0fN15Y3igcIQabM0z8QaKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
