apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    # javno kroz Cloudflare Tunnel: Gateway "public" nosi target (CNAME na tunel), ovdje proxied
    external-dns.kubernetes.io/cloudflare-proxied: "true"
spec:
  parentRefs:
    # javno kroz tunel
    - name: public
      namespace: network
  hostnames:
    - "authentik.zlayahome.ovh"
  rules:
    - backendRefs:
        - name: authentik-server
          port: 80
