apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: external-dns
stringData:
    #ENC[AES256_GCM,data:H8CQAA/D63NPA5SaOt7N24AMFNsH4VSet7skkEFCyVevQnZsOwmwIsaw/5U/DATv0maEgKHDHpJgCgbuFFkzCoZwKwY=,iv:vH1SrFCvrMFV7IxENOhFqYDFkbNNxZ8jmh9CM8iAvnY=,tag:QGW8s5Ku6oyuPNuUjSfNcw==,type:comment]
    CF_API_TOKEN: ENC[AES256_GCM,data:Z/mKtGFbNDuNkl+U+icaMzTbOJByuRQJKwAus9ZTRgR68Vq8AgYgn0p3ayy5WUib2jhYLao=,iv:kItM4kR2z/ewe+NQodqPvnT8XbrkHh0P0xzoTFCE8qE=,tag:tuzCDmsW1o5IYcVr0APzHg==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV0dmc0g4OHVYU2RjdG1N
            VTNRSkp6OFFVYjVsSWJiK3o3VEVrL2dXa1ZBCmJ3Z0Mwc0g4U1pFSU9sU1FLaEUw
            M3NDdXo1S0htODJ2VjhCajYydkw0TGMKLS0tIHo4WjM5OUtpQnp3R2hpenhKcmY0
            d0ZUSDdxenhiSExvOENPMUJ0c3preVkKOUwDzfUa9daspUv843wFs7SUHiVKBwCO
            koH94D9CgKnmWKTlfhTXNm5ZVO8JfIIwdn3WdcEJmwE8huo7BJdNXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T10:12:46Z"
    mac: ENC[AES256_GCM,data:S3pZ9iZ2EHN7DW4TkS9B7H7IEa/VJIyF8N8cM6ppMulMVTC9pAKxFQs961ETz7/k2woyNVUXBy/1ImOqXoZT42m2RkRuemOoedAOhu1ZUXDfLdTKQtRL79bziCfXgvJNJC7gGJyZGd06gyqeWhxGp/+syESHdhBFRpfUyPzk/Ds=,iv:axM0gKHbeRBuao7F49QS2h2gvbCt2yL+fWgT0KlF3Jc=,tag:PvxsrPIDJDCkI70IrdDwfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
