apiVersion: v1
kind: Secret
metadata:
    name: immich-db
    namespace: immich
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:3/ngErvU,iv:gB2mHNtZ6SIRgaIMyPzAhuDJLDHwz7K6M9V5XEDiomk=,tag:iY/UnxU6s/HVrUbBwQTDPw==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:KGIKWkLv,iv:EJS28mgY1ugFMOG37z2noE60QS8o52gBSsit+tE+usM=,tag:AAAtIErwx6MkQt9ws9w+cA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:KGXIfaKCIRjKVJCOdIvQGfUFlNMtpZOkIcc2NjBYUS9WURYGoqpkVPP4jg==,iv:GvMXykKmRpbvUqDuZwEmAxtzc7kvCt/fFrPS1kV4Dx0=,tag:pbucCRWqBoC6i4Pkqqz0xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByR0VDZTUralBmcWlJdzFI
            WUxBb1U3ZDdwNURlQnYxNUdMZVdLUXI1eFZ3CjEwSC91dlptZ1d3Z3QrR2lveUdW
            SjZ0Wm5uRldIR3dHNllZdXJtK3BzU0EKLS0tIC9YdU9WOWJhZWdrZ2VlWnFabVNR
            R1RqeGNKMW9pQllXS2hpdFJQUHh6TUUKMbd/CPX8z4AQMjisGRRtGsOcHbgjJeSp
            bn7VZ/2M3/uyogHzfofLaQFoHdo+WPJbkgjoxuqDsDnKDbA6opQFTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T17:02:22Z"
    mac: ENC[AES256_GCM,data:Mo8eYHR43goOumic3wsvljrzczc1fnv7/cRzOy/Zz5ELTUr5Y/PXzbTclbe1wdBV1p6TrbjFWaykfZ6U1u/AQkp1GmUrB5zPri812JlDQcC+pibtIsrSl1mznYsHE7vn/RN63rabuyJ/gDvDIylUjM9lemdB3iCL2GHbIfuncLY=,iv:vW4Y57+InyxF/rUtTcS5VMOKUrKraRn5toUkao8CzzE=,tag:vPddAuSY7QPpIN5hqdjaRA==,type:str]
    version: 3.13.3
