apiVersion: v1
kind: Secret
metadata:
    name: health-api-env
    namespace: health-api
type: Opaque
stringData:
    #ENC[AES256_GCM,data:yQg1URJ9m2+vxh/DvPM7MmXt/O9R5kaxaxua5TNJb9GaqaXTmIc6yv3tHIy+O8WZAfuQi9wL9ckcO/szInCXwT4UoiIS,iv:ss6aBLUrqUdkMcaTx96vznLpPHPyYTS3ta5Y4Khp8bA=,tag:UkWpMdtLNRs4Pcx96+y2OA==,type:comment]
    #ENC[AES256_GCM,data:dQ6Y3ZJMLxavCzn52UIRfKSya7BAqyDaA3vGPZVEdFB4uX6sN0aJ,iv:24KzRbhIcl//F0PKw96qNVZuWO7lcet+FUJ8k48+WU8=,tag:tafy5tOrNfQFvbv2BLuHyw==,type:comment]
    WEBHOOK_TOKEN: ENC[AES256_GCM,data:oBAVsyQ3tR9Cv/GHRuXJVn9FyE1oBOYL,iv:i3YSw0Eh4z2lgceE2ye+tO3qBHi99obL+geysB9UuOE=,tag:IXXbDu6VDWu3rk45I0jn+A==,type:str]
    #ENC[AES256_GCM,data:fmCJOIOh4qHlWr3Skz/LJz3+31JZC5ZwF0Ayym5VJNYIxtWnF0q13xUp76wsY1C/coKT80YA7JJ7vBCytw==,iv:tkprtuT/LCZzBqfAxxKcIi6+7ltcyigyiCVAwCfJyZc=,tag:EWZ9qI9lfui2lKtCDdyaFQ==,type:comment]
    #ENC[AES256_GCM,data:MsYgOEooHoe09ntjZovxUF5lHrL1GcyWtsg6NiKd7ZwU+3GhSu3P,iv:Iav85Rad8LIoUoNxI8eT/FV5wfJF7iRdaC5aBKJ8skM=,tag:tNwnTkw1tKcg0onIBQtTcw==,type:comment]
    HEALTH_TOKEN: ENC[AES256_GCM,data:yaqLM3RxbPtziUZU7YkLGeA3W5cjzkWj1EQYGPZXLaC5vGwzp9cXCQv6kuoPXnM4,iv:X8wyewHUyOux0xeDpwz1gOz8mgzMgYCCcoxTnnoY2kk=,tag:HPgsm5Xal0f0y1aQ7ePHzw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsa1hVZklVOWQrR1dWbFIz
            dmFxbDd1Z2M1UzNIRUtZUy9WdTA2TjU3cEFJCndpWC82aTBMYmVWS2szTU5VeW1K
            N2xVTXVFRmxiTnBIWitjQjlLODVBY0EKLS0tIGlYNHFOb1VCRHlicFl6UEZ5cUZ0
            ZzJhMWtNNjgyQnZxa08yQlAxcG1PNU0KC6W+XztGRw4JFpOHvCDNuIBodzGHGjqm
            y3t5dG5cIXOoQyGjrtpXJPrECtEfYT7GW1nJJ1q8Ib9Zm953i6vDrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T08:40:42Z"
    mac: ENC[AES256_GCM,data:VCdpXZ0Ms6ZmhQxO66b5G6+4HoXMv+MJRCwXXQhi1Sh/4D7djj3404u0WYlV2xhNK1W8EgU590h5yPN80+CudNfLweEw/j2peWjZSEMTzgPuIMRklwcpQ8fJkQkiH1tXejWXSM4Qp51S0ynYQjFllVIMaDKTNk1vbFZh2Cx3MJ8=,iv:i5iH8QLma7RS87qe86v8LjT7BznN5RUytwOfDQiNpc4=,tag:1P+rX6zie+m+mPvAj9solQ==,type:str]
    version: 3.13.2
