apiVersion: v1
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:LwlU3M/4YA==,iv:eEewzleHGEfVoSoSO/gz0qR59h2Nn/i7+faMOMFjkVc=,tag:rM+O3jZm7OpM5rW+b//Z4w==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:PzdQ0iT8Sg==,iv:kKaVjEbs+kMwB89TPMXjfMdEKg+oRsg052IPLVEUcTY=,tag:pE2zsFNDqKCzGau5WyJxrQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:VkVpE+OyLqf62HprdG3L/ez4E64t3j5nQGooeKnglqM=,iv:faQxpbDOPwKE/xCVcn/clreMO+djgLrQuZpTd226lvc=,tag:grq1sesf8113YaRuOsC3OQ==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:eBbhoorDcQ==,iv:V/6delg86wstgFI1bM1Hu305zOZqWq1LS9GSN/0v8K4=,tag:8dxzVQMgGTL28v3j7YfyWQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:wxQWTZwcEw==,iv:WFBHFWvF8xML/PtimKn+AbDe9bHZrl48+19GLYzsqp4=,tag:Z9LrxvyPpqFOLy8HYxiJJw==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:2eZnQnI6S9p1ZIaPr5vjq5awGUJcMBq1R41bCceDE5I=,iv:JIL43ChufONchcernbSNQPzUYaVrt5fhail7oK1JZ1A=,tag:mJsFtfv0l7w+rGxqe1XaiA==,type:str]
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:FVofJHxi4qlaPK35NP57joYQ/qszjriF69XeNRGjT3Uh3YcfP/BqzF1xzSUVKk+3ghMH5x+VNsCIpJnZ7+8bNA==,iv:Nl51t748OhRW0UncsD/G8eaPQpBnhtcghHSK/E5hUqk=,tag:KHOCVcEjBt5qkTMwiNDBsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbnV4RlM4MVRtQllsTFU1
            enZEYXF5K1pXLzZiZnFHUmRpcCtsQ0VkeGlVCm1OYllyci9HL0hEeWpKLzhTcVpm
            TjF0Z1BJSVFjSnBWNEhVcnFkRjhXM2sKLS0tIG1PWVFWeWxoaGo0WEZHT3FOV1Q3
            UlduQUtUamQ1V0xiTUFDRXFmM3BOU1UKPb+OKLQ3HPB6C8eT1EWDyoCFWxpIv6fD
            MfoseRB4npN0epQw2Dcz/eEhUre+iK9APQMAK+sdkOs039hYgKnXTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T09:12:18Z"
    mac: ENC[AES256_GCM,data:GoAmaPADQcS4B6xAdenzl0b42JAuXddak1FMQsQNdrCJE6F8ruMahZJSRn6vtap48LrWOeq4ItE+o4572cY+4qW51Q1hbC6KQsbBBvB8QsTNQCCGqDK/Q+XjPPRwZio76EGBuHfgCSCNX+kX+/eBx3PlMvXutwUQTMbZZ7OJZ88=,iv:CHobO7VDayDKFZos8QGSQL2romfw6bMOEVMkHZ0J/Pg=,tag:JVUu57uBZwrnL2rWUj7LJg==,type:str]
    version: 3.13.3
