apiVersion: v1
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Dl9RSeOhAg==,iv:v13VgPkE2KBA+/nOaeaGIgr2/EStA9R2ARKndOyxh/I=,tag:8Gtlr6anEJFCTBVWU/ebNA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:O48dH6xxkQ==,iv:goSC9X3RJ5bJErROdE+HsUqKMLVWeet5vfwa32q5dyQ=,tag:HyvmBxmO9XlGSpCm2rncvA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:9nHsh34ocJSTxnl8UfSDT4BCX8UiLBnfE42JuQTWzCY=,iv:nhtC0PUZgqKluKEVy1nvD+3jrCGWNZA3SGEGSDMtalI=,tag:iHBtj3Za9e+v46cbBK/sZg==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:N9G3mVFzJg==,iv:+q3I/X8KSiO1M+b+/eQwBpE6/M/qOzU8Wiot7omnJfA=,tag:gwBXOnpj3+QRNN23KmCk8A==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:AZMU64ps/A==,iv:tyRWN5EtgtJljSVNTo3VIiXVtgaNvQZPcqFqRFxRJbU=,tag:aaf8tYN72aHNrj4q8NIovA==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:6luubXiwIHaUeu4Py8osabJP343ASUh9+6zPw19BaOA=,iv:XYfSYP8tyV8IWeM9n+eHCfbwR+0SCo83rQvKQ1+3YGw=,tag:Hccwr1PtdtbjlwWFlYGX/w==,type:str]
    VIKUNJA_SERVICE_SECRET: ENC[AES256_GCM,data:hiop6hwpq0UdbqaV/t++ETdmAFpuVkISKtuhpzcxF45zPbKaWB6vOSE/7icfGnOInWaKQ8MnCIXy2LuMtaJOkA==,iv:tUbBoSWbl6NY5aNwa38AixmaJQfgO6ABBDCOQwzqrkU=,tag:Fv2WxlH552lGT00YRGEgWA==,type:str]
    VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET: ENC[AES256_GCM,data:sX1wEbjcgWJ75AQmoU/Sx9wvzJ4zS4xsNxBsYAbGWlPbRwfujtYdXDC2DGYTlrY82CeAItXacFuRR7E3EnhcG4QNmIYmyxT6/L0kF6EdzJu5QUMYlbOAgLcfCfeblpMD6SufcJpDai0WtMp8QLRvb590m3UZ23Hwuibxl9SV68A=,iv:ubIWlbFkK/DeuFDAVVypq2z5Z4GJwudpQDNWDIt+3NI=,tag:AgUgPCur5bE99Z3fmiGc1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyclh5Y1JYb0piTU1NWjJM
            bUhGakZNQWVnSU9YR1NMZHR0Y01aeUxlZEhnClA1QnY4UjhGT0NmMWlFVkhobHYz
            NWh3WFBLeGVWZGxqQWlDR0JVdS8zMGMKLS0tIFZUSHQ1UzV5cXU3VmdhdXVVOXZS
            WjZvZHR2U1B4d3EwbXNJV3NKeXdQT28K+c0EGz8HfN8x7lAs/rIy17hqAb6ro40T
            k8roqQstX72smEUD99g+dhTkJltqV9Q3dSW9YTNrkW+jwDPdTdWQUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T10:16:48Z"
    mac: ENC[AES256_GCM,data:SDVBDTjoKdSw6pvZl6rKh1j1nhXdW6o1jeAU7fEQI9245jFxFxNFlbfle2/0DY7umuCk6Vudwm4NXpjjPZRg4TYRIFbbWg7tgsd21l+Q7AsxjaGWRUQGMsOzEQlgYdhp+v2PTyWBSgFvIyUumAFvnuv0Lq2wWBqaGvaaDDesBpE=,iv:hJJm5thnHJwEN1ceobaR75Az49mkL1zZjaHh75+BgoE=,tag:Ti2kuB5RfOuvZ05pe8BrqQ==,type:str]
    version: 3.13.3
