apiVersion: v1
kind: Secret
metadata:
    name: vikunja
    namespace: vikunja
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:MeBoz1BrtQ==,iv:do5NolCbKOd2QZOHnREKrq5m5Y41PDTiQjt+iuDLpNQ=,tag:KBDwRUxoEM+DwPwuOaC06g==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:uKkEGKNsyw==,iv:zagioL1LbQvtGr9SGS1oLDNT0QImqyBA1LGQE5ZRNDs=,tag:O7atTDqQRIMMCK98IU0LiA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:BFt7KRpYXQG6FZCkCjwKCpEZqSkdvW2SdZdJdhT7t/E=,iv:t7r1vEljbf8l4hwKPVCPbrrVTIYSAr/9d2kqa/02RXo=,tag:2VVJcWonP8uDGK1wN26+hg==,type:str]
    VIKUNJA_DATABASE_USER: ENC[AES256_GCM,data:katUNNUEqQ==,iv:SWWtVwPRiqyDPMyCn2c73GmSCoXBXhto6FwNq+/cScg=,tag:E1Ds08Lrmv3Ex+VOKl1wkQ==,type:str]
    VIKUNJA_DATABASE_DATABASE: ENC[AES256_GCM,data:HHmf+VdN2w==,iv:pxRqc+e/ctRacTj5kbqAsbZMkBHYHoUiVUJeVKbfFsA=,tag:fQRgvB0elaWEkv4Zc9l8rA==,type:str]
    VIKUNJA_DATABASE_PASSWORD: ENC[AES256_GCM,data:SOa7etor9lADreT6gl4mSH5PCB8s24huIzJMZbCMGeI=,iv:heap5FQaoOpl0ZIZKuUMDAeT1GFUU1ojygLhzGtXdeI=,tag:IuqG+pxtUzMm/7XQMaKSgA==,type:str]
    VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:3HAxMkijRLIObIIeIw/5Zltnw63KD/rBU5tB8WwAwYCJaVhTnwaAV9Eqb4c3XRhIzWRq2e7W+hKPIKssKXNulw==,iv:2NxctWAXIA4rzVOiCXNh6829SarFM7Vv89/6Pv8nbU8=,tag:z6bXgH4jlfwLb/2y0EXIDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZREhiajdEMEN1WVJUNG9Z
            R3NrRDRGaFRvYmMvb2dWazJhVmFnR1JuTXk0CkxmVHVMRUZRZngrcnVPM2t6ejI0
            R3NHdm4vbzk3bmxGNUtjUlo0UFcrZmsKLS0tIG10OFJTYVNURzM1TzlZdzJ4YUxp
            aVJ6U0hWVnNzU2U4MzlKemhQSm9MQmMKm40IZi+YvAs7ls0V6OI32UwYxOsQlwqw
            JzdgkiHzd8J5Y0hVXOTaE4XAeKtBRetXPp8kAAQ/djw2M+vsseAsSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T09:08:41Z"
    mac: ENC[AES256_GCM,data:eK/U8CuyJOL6P2QqhZ7PkjW4x28yDoxPUrL7H5pomsFaFdSFmxcbnfNeHG6bjpR+6x9A/bavvftBJ4dSqbsTYb5dnXsW6o2ouk26tNxVr8z3rw3HW9Sg0D4UWyy9PwmGKzNgNOmS+9Lj+mr2nh1f2MNtpkqN0JIlmGcacPYI73U=,iv:8m9G4RR78HCjl3ayr6lQSCczJlkwLScIh6L0CffE5Pk=,tag:7ZURuu06hHULnJVqa+hezQ==,type:str]
    version: 3.13.3
