apiVersion: v1
kind: Secret
metadata:
    name: hermes-env
    namespace: hermes
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:/QSdVGc0F9NIZYYYD5fl4ZYsr8c8COzt47qyaY6FRds1qpy0ooCXRrqD4Q7vdw==,iv:D8fHtca7mDwDt7Fb8hmc2/jQdx7Iu3p+Mm/PvcR9Nfs=,tag:ZW1bPKvSDAsxyrtBxmI8Ng==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:9Qj8TJN5JSJZ,iv:cq0sEgOcj9TQls37YwKgio7gTRkfppQydPpEOMdjLsk=,tag:hA4uufIcsfoO/lTzZ/jd8A==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWdYcEJ5aGN2c0U3UEVX
            bzRkU3VLQVVTZlc3ZzNJaXhUSTJDUFhkclRvCmlQQmVCY3BRWXNxZmxOZVc2V2ty
            NGpXdlhlMEswNWxMNzA5b0ZaTDhGbDAKLS0tIENtN294a3hVcmxFWStWUE1qa1lx
            akFITjdkWDB2Ulo0aXlOa2dITEtVQ2cKsw3CTuobWqTd2bsiEhHiGbF2Z6lQXMdd
            5PlsHkmLxUQOMdxWrjy533Xswdlfzc68YMyhpFWtK8SsENQwuC+w+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T17:03:01Z"
    mac: ENC[AES256_GCM,data:KzpZgaNZyB60JlCycyy3LuEiIl8OM89c76grTguofU6bB7VQjbwIISE8tJ07giiXi26h9XdOZtwcVsvTD42Gj5cZExDAkIB3NF2hXrtUrc3RFhgl65T02UjiVFsOk7JzAix2/3xkBJfpf+amS7Vm5pjxeKjZ8UUxYbNPWFO01hI=,iv:PPxmZQd5l1e0xzoiNRhklzbyvpNe32iBAngOrG/L5MU=,tag:i/fhDU6r4YfgmvDRB89o2w==,type:str]
    version: 3.13.2
