apiVersion: v1
kind: Secret
metadata:
    name: hermes-env
    namespace: hermes
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:/QSdVGc0F9NIZYYYD5fl4ZYsr8c8COzt47qyaY6FRds1qpy0ooCXRrqD4Q7vdw==,iv:D8fHtca7mDwDt7Fb8hmc2/jQdx7Iu3p+Mm/PvcR9Nfs=,tag:ZW1bPKvSDAsxyrtBxmI8Ng==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:QJ6coIfpnnIO,iv:IcAIucT7kZfpV6bzs24Tsv5pOmzzXQEW6U8aGxazqp0=,tag:L+Ccx498clPg27GLZSs7Bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWdYcEJ5aGN2c0U3UEVX
            bzRkU3VLQVVTZlc3ZzNJaXhUSTJDUFhkclRvCmlQQmVCY3BRWXNxZmxOZVc2V2ty
            NGpXdlhlMEswNWxMNzA5b0ZaTDhGbDAKLS0tIENtN294a3hVcmxFWStWUE1qa1lx
            akFITjdkWDB2Ulo0aXlOa2dITEtVQ2cKsw3CTuobWqTd2bsiEhHiGbF2Z6lQXMdd
            5PlsHkmLxUQOMdxWrjy533Xswdlfzc68YMyhpFWtK8SsENQwuC+w+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T17:08:07Z"
    mac: ENC[AES256_GCM,data:BoeO0Wcih82P1NpJnNljMFOK/eTSqQpPcdeo50CbkNMNw5vIdHIIfOEGNTkgV/Fz0j/TEPsR1ybAlVTxuQOpnmYtSRi29Du2N9t12fd0njGKh24jIw0KijHdP5rgLq3oaID2Kycq+hv/6EN5ZlUWxahe5CIrYuMep8Zyz0oq0UM=,iv:/WJf8O6nAvrkdHc1iTpAin9b8RXAxOeyYGvZfU+hbBI=,tag:z+Q2i8rL/ELvYo2U6ExVLA==,type:str]
    version: 3.13.2
