apiVersion: v1
kind: Secret
metadata:
    name: hermes-env
    namespace: hermes
stringData:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:/QSdVGc0F9NIZYYYD5fl4ZYsr8c8COzt47qyaY6FRds1qpy0ooCXRrqD4Q7vdw==,iv:D8fHtca7mDwDt7Fb8hmc2/jQdx7Iu3p+Mm/PvcR9Nfs=,tag:ZW1bPKvSDAsxyrtBxmI8Ng==,type:str]
    TELEGRAM_ALLOWED_USERS: ENC[AES256_GCM,data:QJ6coIfpnnIO,iv:IcAIucT7kZfpV6bzs24Tsv5pOmzzXQEW6U8aGxazqp0=,tag:L+Ccx498clPg27GLZSs7Bw==,type:str]
    VAULT_WEBHOOK_TOKEN: ENC[AES256_GCM,data:4pqf9xH69F0zGCTfS0EI5gqHNwzWToQfJRHO2BtopYnRSDsS7Ac4/bDfxRXaXUeFBCJUttKGzrikp1RNLjydvQ==,iv:UdPW8vaYjISZdcKCqFwddA+BlyVSjZ2TlT3Jku4+OgE=,tag:FpdVkoUT8Gx4ilzQ9pG/Hg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:zrAU6xg=,iv:hr8WgyEU75Ncy/4j+ogM8oioHrtDr6Zs/gmA0tvw4nQ=,tag:5uIhuLFXEmwjmfxBL54jqQ==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:cwCaJ602OP36hbRFvDZcGMJ7iV3ZMp//,iv:U7wwWhlGn3gDGguvVDqTQxQOenfrjTcxost7Z7Awv14=,tag:KO6RPIhwyqvB89h9VhMecQ==,type:str]
    HEALTH_API_TOKEN: ENC[AES256_GCM,data:DBo+DSITenQXugN/YSY04z+8atM7+sxBARotwROMpqu6sSRpjmYL9FywP1Iyo9qT,iv:+WtyQZhFzjS4KRp/d/c95KtdJlA5zYDHz9HBrYkxwGM=,tag:qeaDFFukPNZvHZnbHwk33A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYWdYcEJ5aGN2c0U3UEVX
            bzRkU3VLQVVTZlc3ZzNJaXhUSTJDUFhkclRvCmlQQmVCY3BRWXNxZmxOZVc2V2ty
            NGpXdlhlMEswNWxMNzA5b0ZaTDhGbDAKLS0tIENtN294a3hVcmxFWStWUE1qa1lx
            akFITjdkWDB2Ulo0aXlOa2dITEtVQ2cKsw3CTuobWqTd2bsiEhHiGbF2Z6lQXMdd
            5PlsHkmLxUQOMdxWrjy533Xswdlfzc68YMyhpFWtK8SsENQwuC+w+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T09:43:58Z"
    mac: ENC[AES256_GCM,data:aouG6yFPacyDjLuA2yDVXJhp3rdy41DfTzPqHc1p97nUo3clyzbX7RDZ/ngxHPOnp6zukkWTXvylfvXPMnu+ehva4uQHnjb1Xo+2bXLkBjS3/8YTiQrJ7nhe7A41yh52K8WegdmmwPIodFsfQ+YRm28e5aAVclBeLOuRRsTqBkQ=,iv:FEqsp/wBdXmk1pItQjMq0/SU7oKzcOb3RvNwMyU9PuU=,tag:9zMSSbZus99jpr9yucCDFA==,type:str]
    version: 3.13.2
