apiVersion: v1
kind: Secret
metadata:
    name: bookorbit
    namespace: bookorbit
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:/pBxehcJ8gex,iv:thPSb2g51L45nV4bnZh9TtWrqp+uA9EcWpPnG7SPhic=,tag:vV37sNyZN66UU+tRRrqxLQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:r1cBsTjhhqi1,iv:lGAbNeKVJQMYW8O4sQEGbXsB9WBG4Cr/FOeKPuJxQsg=,tag:JkkxsARt3NHGUVFUkQdrYQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kDqmP/5ci90N9ny7Wh+Evhs7O2UYosAg2H1lkWkwkKwjzKkxQryk6SYiOR/rRr3t,iv:ukG/UEh/kJ1/hZHGKdD3QqoQkkidJMyMn5jYUFvnNzo=,tag:9iQHgsWCyvtuk/XZfIhukg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:rZCLTNaYsbFL6UCdYZmSHSi/K7idEHvLXLEKPtQfeHUVFICN8dactMbFfOZ/V7wXQn4wMdCJ6hXCZKXxL5Eu3g==,iv:8a3ugh9TWR+2dNFA0NPLIPtRsK+l0Y7giFsmy82dGtQ=,tag:kEoRCRPXFV66OL8kDpTjbQ==,type:str]
    PODCAST_ENCRYPTION_KEY: ENC[AES256_GCM,data:dT2jiXpxKR2No2uM0uxgqCW+1gAJ7bhMaJ5rlP5Cwx7YqjxBPkct/2kGyepXdwoRNLxPLK4iAZdjoB4QxnR7wQ==,iv:ytN92iomU3IO/19URJH0TnotMHhibjAPEJqKkkfMSVU=,tag:1WngH1Nsi7fpiwFuPZCrkA==,type:str]
    EMAIL_ENCRYPTION_KEY: ENC[AES256_GCM,data:z8agcjPZCTnJPuadb+uQJRf/XDFN0ubzZhnxmaQIZmw1c/jg2M0H2DpaMA5Bj7BfcCOtJ/PnJt+mdEBnLStx+Q==,iv:0xzeoA5XsUm3MzIPHx3SevkXTE2rpH0x0cbrXrcFkS4=,tag:Rd1cz23etPwLJOBjyOj6Vg==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:T8PbM779d0oiDWjv6wdxAjbyUpvGy0wIrHnaGVHmv06C9Nn8t7eF6AUrmNzeZsIU,iv:bB59ev6OeSjltD5Uw0CU6Exwxz+5hoZbTaMZN9tncZc=,tag:3InhHUBOh/TuhGoTYqPkfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRldXTE1uOWNuaVNOWG9o
            T3FlbGlTWTdBVTRmak1BdzNGR3dKQVBqRUJRCkRtbWVQN0dzWEJkYktXZjZZekR1
            SVZ1NTdoVFFyOElWUlo3b2Z2WllTNmsKLS0tIHFRSHB2SFdMREJQeEFKS1I4U2RO
            UWlaM2d1RWp0eTJjZXB1Ukw1aWw5WWcKsxH4N7gi0W2xai8bvMO6cHNoPa3EVePZ
            sV93owmuQi4z4Phlh4UGv/PrfE8iXfoUr93lo8ImudvqQpmb6bcV0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-27T15:07:57Z"
    mac: ENC[AES256_GCM,data:01eM45Xt6RzsO+jFuRaYHx3lFr9KJfzg0EMQVMALpjPQxTJVBrkhENhBB0wjDMQVmDj91DTd1H2RdMYjBK6VUGplD1y0YssEWBj96rBnam/C5sOQ8ayNpz330mg7vvki8mhXER8dfYgNvXisvUoj9YapNuH8X1poABmh5v6V+Oo=,iv:TCl5FSZDRAFwEg64nXMnOJlKH9yF5ARXrebrcZixueQ=,tag:akul9PlFu6WIDr7MyXvBLw==,type:str]
    version: 3.13.3
