apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
stringData:
    credentials.json: ENC[AES256_GCM,data:Wv8hBqtBu/pvgahYKiiopP/FeY7APxUAhYorUGgoyFN1Z/Gl/rT2L8RtjcLajOHRqB4bRR7h1zt47H/WRsIYKctGkoerhOqk5+UPWK14XTK2OOSoneeK3BBxt57Aa4KrAmtWIO0Y/7AARcyuqztiMux3JAeBa6KJwZucCw2c7ql4Ld2xAFbD4ypfhkZgb+rTbjOhhb9EY0NjiDLpTxGwRD6mII2O,iv:Gk+/v+wqBcuI/Utcxp3d3gkYe+h1aKlFK07fO0wxaj8=,tag:oZJOSwPuja98SFdAfQEJVw==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdHhXdEFkWHMvOHRhSkpE
            MHU4VlRLUlpMQzNWTjRZSnBHcWY0L2ZPNkd3CmtmczRFVXBhRk1uMTFQN1VIeDBM
            TFhGa0lJMUZnVnRUSXNNSFRBV0NMUjgKLS0tIDhLRFJVSXIxNjhzdUI5WkhvL0h3
            a3F0NW5yWUp4bVNiYW81MFpmejNWajAKthBaeHqcVdlcN8OGNA7POkimEXRVjRMx
            5w8ucbT3KQztMrTrxXAWJozoV7gOmawGpBJvv6Ys8gqIucjTOpLFVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T10:12:46Z"
    mac: ENC[AES256_GCM,data:YMLXKihvIfT3VdCkEakE+UrS/La1/EvIVO+i+g6nAR4QIrHd5pCrbKCrqkZ+YV5CV1hr1TqiG6wbl7i4OwMZCkMrvJJc1UaMDCbwdSuz+xdfDi1NCcwPthBIPu3Rc2OHolAJ12Hti2adEp91SCgTahZTQvXDcx4ULDy87l+O6/o=,iv:FTI//Iq1Pg9KNroz4gjxsc/3SC2wuHyIzxL0WVB1MnI=,tag:yiGd4gKassJ81PrLJe5JNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
