apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: plex
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:GqtRz8vVfQGvcKVs+BbA8aYFT2pSXXzxMik=,iv:DdYa937dys2JiLlDh7RMGpOuJyvCMHWxLHk/30siGm0=,tag:TxdmM8cIBqWYpowTPbpfPw==,type:str]
    ADVERTISE_IP: ENC[AES256_GCM,data:vtDdlSJBAVQsv4XUGoq+UCbQ8sZBg1w=,iv:aY6qZe0SLYt0ze9LHr6+Dn8ao0ZQZ0ouXpwbjTQ+Q8k=,tag:EM9XuZLn/jgz8xUzpqd6zw==,type:str]
    ALLOWED_NETWORKS: ENC[AES256_GCM,data:hcP4oc7DQnaIxw7oAlkzCjpaDXlob75IM4PO8vfZId39riL7bTMlz+I=,iv:L9rVmcq1p1G7kj9U1BDXXOPRmpDj0w2GmkIpzD/8qBg=,tag:ai29xmXMfvsrRMVxwxcRwQ==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUGkyWVdJeUkxazhMdUZm
            dGpqckxTb1RJUGtKTVpBVVN4d0Y3TVZLVmhRCkRCMUlDQUN4U0hMMWxvWkhnY3RO
            enR0US9BUGdpTDU5L0ZvcWVSZG5NU2cKLS0tIE9SdnBUbnRITDllS3VWaFNJb1RB
            aE92TTl5OVZmYUhCMlF4UXpwditmbnMKI7gZKM60I8oAFTmUMnIj+tRIXYtXtsHB
            jgKwkjibsLGzFhIwUnvYNUoCZgvp/4tqNH9WrcepXzdHEYX2hUadUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T15:33:50Z"
    mac: ENC[AES256_GCM,data:Dx0fgr5HgEJTvCUKCM8R4nYuWn+gLhBt0B3hkQ52b5MnPPWDsz1oOrDTLyN6tNBOYyMKalJ4C6Rk2MBVwiUGQ5+5dUwVIhmeo5Gu2hWS8f7LbqVbvDFOBZ0/Z8Egn0Sd7hxp2zqGPLN/IHT2zdTG8fit2v7h4mZc+d4kFza+cbs=,iv:MB9ARHJ+cNtnXQMBnK+YPA9lLLhbZIOa/vZAX2yOYBA=,tag:Q6keqHzEyVgvbJLo+1R94A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
