apiVersion: v1
kind: Secret
metadata:
  name: plex-secrets
  namespace: plex
stringData:
  PLEX_CLAIM: "claim-REPLACEME"
  ADVERTISE_IP: "http://REPLACEME:32400/"
  ALLOWED_NETWORKS: "10.244.0.0/16,10.96.0.0/12,192.168.0.0/16"
