apiVersion: v1
kind: Secret
metadata:
    name: plex-secrets
    namespace: plex
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:GqtRz8vVfQGvcKVs+BbA8aYFT2pSXXzxMik=,iv:DdYa937dys2JiLlDh7RMGpOuJyvCMHWxLHk/30siGm0=,tag:TxdmM8cIBqWYpowTPbpfPw==,type:str]
    ADVERTISE_IP: ENC[AES256_GCM,data:k8AIX/Kghc1hrfqokJ95wBFp20VZDJS2bEIE,iv:YUCwooanKRPwzcZp32b6yCYEel07mlsAvnkdUYb9/Os=,tag:4+qXCQ5id+aLbv+GB64kyQ==,type:str]
    ALLOWED_NETWORKS: ENC[AES256_GCM,data:hcP4oc7DQnaIxw7oAlkzCjpaDXlob75IM4PO8vfZId39riL7bTMlz+I=,iv:L9rVmcq1p1G7kj9U1BDXXOPRmpDj0w2GmkIpzD/8qBg=,tag:ai29xmXMfvsrRMVxwxcRwQ==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUGkyWVdJeUkxazhMdUZm
            dGpqckxTb1RJUGtKTVpBVVN4d0Y3TVZLVmhRCkRCMUlDQUN4U0hMMWxvWkhnY3RO
            enR0US9BUGdpTDU5L0ZvcWVSZG5NU2cKLS0tIE9SdnBUbnRITDllS3VWaFNJb1RB
            aE92TTl5OVZmYUhCMlF4UXpwditmbnMKI7gZKM60I8oAFTmUMnIj+tRIXYtXtsHB
            jgKwkjibsLGzFhIwUnvYNUoCZgvp/4tqNH9WrcepXzdHEYX2hUadUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T15:36:47Z"
    mac: ENC[AES256_GCM,data:p0JcFbqTZ+kXq+sMbbjot8WdEJmlUahq0sghC0s2eEBuaKvN1lyA2fw3T8buHml1noXzKGBabNZK9AWo4f1MZiCKNUgLAPkuDAyWlbBYIC+CT6RfWwUTcksypMMrEqBM4dE/3wuQe2OmCM8uwDT0G0YJHlMfzklsz10jSu9DLTc=,iv:nw3bTJmq4XQ5DDUQ3l437TlX/T+HFMz9C6evraa84t0=,tag:j6/+Slu53gumOHBqfuWk2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
