apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: recyclarr
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:kvU1M0/kI8BDqeOTYG1JFHs4yhiFeLgLl8k+dWkIe+4=,iv:ojjcJuN5d8DK5xYF/HiJSxqn4iAE0UllKB2t3ohMoFE=,tag:xYXp8tYhtS+73JuBN8U+fA==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:oW+7dRnedo4hvmsk2AGVIG7ND3Aqp11kGT5pv3fDLZQ=,iv:moUPzjdZcjhpwg4EyG3fCagJQ+bGtJsAakx9Dh7i3nc=,tag:/gno1MSEnvKtalCh25zRQQ==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVWFWUWgzbS9PSUM3TFRq
            eUNLaHNVRnhCa1BXMVFXNDV4NEZ1SmExZVcwCnRFRE45NHdlSmpHdzgrSHlzanFr
            T0l0Q0llSnFtZXhTZVkvMGNXcHFjUlkKLS0tIFRmR3k4K1E0NGVxWnRzbjlKVGY4
            eVpVaFB6UFZ0OVJ6Qm11RUxsQm9HWGsKmo9YNL9ApNoR1y6yCMCsRPzNkELJ6U+j
            T/03q7fez3gOgfnN92zpMsJK+CxxBIFCV9lxwxuOl3hjY2yLL3VUUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:26:19Z"
    mac: ENC[AES256_GCM,data:9P/t48Da76EeQaZGDEGx9CfAwIhJc8OoONIYzDMgJ46Raij5qW13ddLnBlwG4IWKyQ86gUulBXdobKdPqLa5MiEDePW1D/1fzKCXmr0cBBV43zL4nY6FpyDwzezgeAzJv0N4PoJpbmrvu8yq9xMlY5TmSKjOk7yEA9iyoUNrSLw=,iv:HYF9jyLVXNdTsjixRZyTa3RKHi5IuWMAaNfvWXioCkk=,tag:igvdseqa2+t0+eT/pwkmBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
