apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-mirror
  namespace: obsidian-livesync
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: vault-mirror-nfs
