apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
    namespace: obsidian-livesync
stringData:
    config.json: ENC[AES256_GCM,data:AQvMjLspLVs9jZwY+XaHvzsvDjlPGo2RETUd+VrL9yieiEmDUyclA1+ce2O4h+qXU0R6R4uSuHnZ9hBFszjkMAs5Yt9vnd32cRTh70852ehRRrzdZ5ZUxBZXyRASvQpeTughcoBb+81EA7Ctaeoa5LeaARDoZ/OuwBghOiOEZRuQYH0zU/1RuEsUgKu0KvFtowcAwklWKp87A8yAPyuhQD5YSneRO9yGAfRj+WxmjWWIiFEasDOkskJoSiKIVq2oOW5oPmHVKhx+RAzJIJMV9dn4lfryv3XEc89lBzp0AcrxM5WVcnBLiDCPWlu9oC+a0wUCmAwz6QPnPd3tRrhBYZh7EK6jxN6QHKmmiByDvNI7zEDyWao2XPpJNR1OI5L8lN63jcoL+X8IH5E/o+lfGd72PrBgJocHvKkyhgTTYzi/hNRxb+fOus6DiVxC/cLYEIlIc/Gir0qQXu9i44bObsg03EWHnxqPL4s/CIAq3LqDKw1lUPTIEhlDUfMwk+RmML4g9MDPTOt+HUAH5+RuagLqdk3Uv6ITvBm2IsL3bgmX1voovyGXq2OMGlmZpAalmiJCKr4NAZYIbfVX3LexiOobUPnwUYJMBVqQKo3GNt3VK3PC8JLs21CH8ihflKaULzQ2BLwvooN001HxTn3tReAqRsIbPmdgJzcjigq/8KrbL3WvOd0a54ye0NheAcB+nJRIVnlWzTN0mSNl1NvLshLTqtTXAQ==,iv:BVQhNqJILQG4tI46gQSxWRpdLHjKJ+2aCwPo0l17gs8=,tag:vDt8TDggMyu4/QmCdNcH7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXBYU1J3cFJuRnhMNC84
            MDZrczVpYy9aa2NtbWxpbERwY0o0NDdhWlc0CmpPdWFlVUU1N2Vmem9QVjZqMDB6
            ZW80eURCUFhXUzJKREI4d3Z6VXkvSDAKLS0tIHRBWWp2b1UwNzFodkd6aDZ5cXNL
            YlJ0WHpnUnR0YjhRd3k4aUhDRSs3REEKcXKuqbQA6nqY0QXc6l7FP1HFoMOPnDEG
            zGIFGwAgrcms40Is59+n5H/k3B2xdWkT9kZvtleqZG47te9HFgjrog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T16:27:09Z"
    mac: ENC[AES256_GCM,data:327wLZDMu8Dq/TWwGTLo/ibzZ6bxeDjjp9/5GXGTu0bg0ffqqbT8P6JnZgqtmR7hOI7WSf97mFXLnTMd1bTs8yK7qklT5wNc/s3Dgovm9OCRG/ejxPAqvLhP+j/ri6VTOprUKHSnaXl24KH9Pvyof/5HOKpLJGM7fO4e3DxegTY=,iv:XMY3vs5KHe7Xy4BI/mRTHaBjQb/jHQ3YOD3SWfBfRVs=,tag:G/XFvQOXOfboJ4uyxtmHlA==,type:str]
    version: 3.13.2
