apiVersion: v1
kind: Secret
metadata:
    name: livesync-bridge-config
    namespace: obsidian-livesync
stringData:
    config.json: ENC[AES256_GCM,data:+xqA3ewvkPdOeOg5CsNjOS2W3O2Vp1gAmQwonnslAHScae0mZ9iWK39owfGWi+iwywGRa4NDqEpLgWDA1y88D+F3KN33PwhAbDlwVI3Tn/b3g6sE5swMS6F2J914Jw/hgBoHN2PFSIDj6XppK810nF3REu5vrvLjbd8xJ4qmrsWCdyQVSu1irkRDanlFsucJ2wRG0gxdCpdPltq2dNqo3tdjcFvl2kHNrH2RAx5zvhd8vUUvQZNuyZjNef+hUfJoCr/ZuW+KNdC147c/yZoxlR1bRYKQHkuxilrS4Ub4MtLYrwjSazDa2GSGm7tc6x+m5tUEA5z8ZpIKD2kiCdniHP7SItqibXau9adfjReNsjd3mv+elKvZew1VEDkcEI4HSDGknz7OsDGRF15EmQFD3KtQe7ZVA629Q7WAYvfIrB/Q4iBhj9fmx1JP982VUtEF/a8gbpVH21MVHcbydThxroOkXo7EzJZq4aFLnCDM7OuWQ04PDHODhJ+MmCNiB3MvvpNsGnA6PQIalFCNut1FKmeI0EysfngVlxob3bWTRLKzb9plRRdxYWlJWjI0PgDPhKlxDocge4Dvrdl4CPOKX1jzJFEBdjDxEMt8WF6l5ZSEkMe3FOHbLcW61DFKjYUKbdXdV6Vug65UucMAYGKxu0nusembsEBYNUEwVzbF5kDmD2CpXeUG0Kxbu/jgTrmZrPNDT0WJg9iOEtnZiYgYspJ7WDrFMpyepnxQcZ4T+MO0h+s9B5iSf5r62gJWnPnrUGwNIw==,iv:M2rBt5bNB/H20H4IUjmWE8sueNeJ9iaDeAZqJCfrFMY=,tag:PskXTPqmg5Wi0VZpBEV2Bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXBYU1J3cFJuRnhMNC84
            MDZrczVpYy9aa2NtbWxpbERwY0o0NDdhWlc0CmpPdWFlVUU1N2Vmem9QVjZqMDB6
            ZW80eURCUFhXUzJKREI4d3Z6VXkvSDAKLS0tIHRBWWp2b1UwNzFodkd6aDZ5cXNL
            YlJ0WHpnUnR0YjhRd3k4aUhDRSs3REEKcXKuqbQA6nqY0QXc6l7FP1HFoMOPnDEG
            zGIFGwAgrcms40Is59+n5H/k3B2xdWkT9kZvtleqZG47te9HFgjrog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T10:24:58Z"
    mac: ENC[AES256_GCM,data:Va3vxO/J0ELQPxoo18yqckWta2mutfL8DfTxVAs4pkFQpDWsyYLy7nXMndJVytTEM4uTpgnQqjlh+L2PsCHLGadti6Ous3KlMW9OBeHeUwAW1cbgSQ0cnrAFypMbi3/chVNpQTxab5raUKc7aagt7MXGxg6M6/gmF+V6ySYykJQ=,iv:9CQGRg24WTwS1ykG//EkP55UU8sO6q12WB3phbaAnAE=,tag:oHB3jK4vvMdVFCfRan21cg==,type:str]
    version: 3.13.2
