apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: obsidian-livesync
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:rzniiKE=,iv:Jbo2p+mDixsflG5n0SpwyuAj41FEYqdVPApF8f/Zj9w=,tag:U6WI6enaOIJJco788kUMXg==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:7j5CnHpNpvJkiXYq7D4=,iv:jmYPp79Q2U8XAdDvm8A7BaES03cz04i8zuWFhmeWNiY=,tag:+552kug1sAL6Xgtm5XdlFQ==,type:str]
sops:
    age:
        - recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVanhEZEhDY1JwZjUxSXhl
            dENZcUd1OHNEWDl5d3I1MlVXMHd0N2hrSjJvCjhvTEl6cmVib3ZYbDQ3Y2RRTzY4
            UmJoUVRjblV5aFpOSmU1cktlbFFMUzQKLS0tIElRWXA1aGR5Mmw3Q0lCdHJwOE9L
            VUh1Z3JiUEpvcUF3T0ZmQ216NWRsTkEKZ99oxyusk1jYu0fKO4191xq1jAjL7cAE
            K/h14jGcnHkn3/7Apdgc3QAmn4P+ThmHELiuDAYI5M4Eb0g8SMCMXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T23:30:02Z"
    mac: ENC[AES256_GCM,data:/Rf+zI6WdCwKWVOgNoQAsETp8qxk+9eh2VzWrZupiZrpFiCE2h+XpqkNypKK+ZaTsSfoCVp/371E1baTX6lrFFK7egSwkRYIrdvKIqgBehYmQ29/Yr1Zg0zG+5WXYnU+wINIQ5a+NFZ47GK5+IL/aB9yaPbqFLmR9r56U4pN+uU=,iv:K+sfQy7Y+Z+MadFqARWzCjGjYW9/pOj4vMUWyci0KbI=,tag:bstvk55ryOQw0JQio4aLEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
