apiVersion: v1
kind: Secret
metadata:
    name: vault-webhook-token
    namespace: obsidian-livesync
stringData:
    WEBHOOK_TOKEN: ENC[AES256_GCM,data:5Konlm1CGxrGLTmKfklRjRkNujP75XmOGFyVDGsfA3/vXJeAJgVF7oS4gBAw0bW/Y01KspImRF1Ki1n/UfDFvg==,iv:yjOoMbRuL9l4ejeOLdnTWnLCnDuR74+0kwHMGBRlnQ0=,tag:rPernGfmeqY8T1kPV8PkOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUDE1NFVMWXh6elUvb3Ju
            am9vQk5XT2dZT2phZXRzdS9RdnRubkhtUDF3ClZpSnM1ZHVraHF6ZmtwWkxuYlh0
            eDNhODJNQmErOSt2aXg0YVNCRVBuaFEKLS0tIGM4cFBMUnc5SE53VFp3SUhxYU1F
            Vy9ESm1sa3FBZzZrNi96Q0FISWpPRVEKujbdStdeZhZxe5vnFXSkXYuc/e38mZ1g
            23US+7PPv+NPZsmyY+goFc/J8vs9Y/tj8w32WJIdC60umN8r896mxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T17:53:10Z"
    mac: ENC[AES256_GCM,data:L4orHppCpu67CaWkN1Yb5RkqB9P63SFtjpQrTctT00w0tHp+psGWNq9A6/zbaQPyalJLxGzPm1dqP0VF42JoxX2yxcZR+n6RTHeaV5i1QW+7KVxcomQIar8L7V7x0tjWGmcSPXLhjBBlGpuFj6dD1ftWroGQez+I5y5pxR4uges=,iv:AZMEgQbl0CmaRMGRtGzi5heudsbySI4dnvCkNbpRCAc=,tag:W3HjD85xhJuceSlV1hY7BA==,type:str]
    version: 3.13.2
