apiVersion: v1
kind: Secret
metadata:
    name: vault-webhook-token
    namespace: obsidian-livesync
stringData:
    WEBHOOK_TOKEN: ENC[AES256_GCM,data:5Konlm1CGxrGLTmKfklRjRkNujP75XmOGFyVDGsfA3/vXJeAJgVF7oS4gBAw0bW/Y01KspImRF1Ki1n/UfDFvg==,iv:yjOoMbRuL9l4ejeOLdnTWnLCnDuR74+0kwHMGBRlnQ0=,tag:rPernGfmeqY8T1kPV8PkOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUDE1NFVMWXh6elUvb3Ju
            am9vQk5XT2dZT2phZXRzdS9RdnRubkhtUDF3ClZpSnM1ZHVraHF6ZmtwWkxuYlh0
            eDNhODJNQmErOSt2aXg0YVNCRVBuaFEKLS0tIGM4cFBMUnc5SE53VFp3SUhxYU1F
            Vy9ESm1sa3FBZzZrNi96Q0FISWpPRVEKujbdStdeZhZxe5vnFXSkXYuc/e38mZ1g
            23US+7PPv+NPZsmyY+goFc/J8vs9Y/tj8w32WJIdC60umN8r896mxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1363g325u7ulp5xkunn5tf6rhunkvqftn9hftz58ja5d3u22wuq8s4hje2d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T08:47:50Z"
    mac: ENC[AES256_GCM,data:RCWwR+bKeIMgGEwd7/HYUI8TPR+5FI8KfALN84h/gn2Cz3YYM94qsvhA4+IFD1Goe22I43J59dhjgy34tDgTqidH1x7gudL7/0L3QbbcT+B7LiuKOLaSUhf6URYiUv1ywk6EAG5Xx78woU9EO0rNjw9TQ3I2tvXHjo4hsfiQ1Zs=,iv:bRN2t9z8S2GnXjpJx+F6NQs9bibLIK29w86UGjpwPkE=,tag:CweFf100jMSxJiyIzSyVhQ==,type:str]
    version: 3.13.2
